buzzwords:
  - trigger: "anal"
    reply: "ein weiterer centimeter mehr, unsere ArschlÃ¶cher sind nun *%d* groÃŸ"
  - trigger: "huan"
    pattern: "\b(huan|huso)\b"
    reply: "Und wieder wurde einer zum Huan ernannt. *Huan* ist jetzt auf *%d*"
  - trigger: "tzn"
    pattern: "\btzn\b"
    reply: "ğŸ™„ Schon wieder ist etwas am Arsch: *Tzn* ist jetzt auf *%d*"
  - trigger: "bier"
    pattern: "(bier|pils|saufen|saufem)"
    reply: "ğŸ» Scho wieder am saufem, damit ist *Bier* jetzt auf *%d*"
  - trigger: "420"
    pattern: "\b420\b"
    reply: "Nice\\! ğŸ¥¦ *420* ist jetzt auf *%d*"
  - trigger: "weggesynct"
    pattern: "\b(weggesynced|weggesynct)\b"
    reply: "`rm -rf /` *Weggesynced* ist jetzt auf *%d*"
  - trigger: "sync"
    pattern: "\bsync\b"
    reply: "Der Sync ist stark in diesem\\! *Sync* ist damit auf *%d*"
  - trigger: "obegfoin"
    pattern: "\bobegfoin\b"
    reply: "Immer ist irgendwas kaputt\\! ğŸ¤¬ *Obegfoin* ist jetzt auf *%d*"
  - trigger: "lel"
    pattern: "\b(lel|lol|rofl|relf|lmao)\b"
    reply: "Und schon wieder wurde extrem laut gelacht\\! *Lel* ist jetzt auf *%d*"
  - trigger: "kartoffel"
    pattern: "(kartoffel|pommes)"
    reply: "Kartoffel\\? ğŸ¤œğŸ¤›ğŸ‘Š Pommes\\! Schon *%d* Kilo zugenommen"
  - trigger: "vapoctl"
    pattern: "\b(vapoctl|klick)\b"
    reply: "ğŸ¥¦ schon wieder vaped sich einer gesund, Bereits *%d* mal wurde Medizin genommen"
  - trigger: "ziehen"
    pattern: "\b(zieh|ziehen|gezogen|ziags da nei|ziagsdanei|pep|pepp)\b"
    reply: "ğŸ‘ƒ ziagsdanei\\! Das *%d*te mal schon"
